services:
  - type: web
    name: dancecomp-phoenix
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "80"
